### ISSUE TITLE
Foto de los usuarios

### ISSUE THREAD

**Issue by hugolatra** [GasparMDQ/mdqrapp#17]
No se muestran las fotos de los usuarios en el listado (solo lo pude probar con el perfil de Cris). Sí veo las fotos de los admin.

**Comment by GasparMDQ** [comment]
Me pasa lo mismo con la foto de Cris. Lo extraño es que la url la carga bien, pero facebook tira un error 403 (no autorizado) al intentar cargarla. 
Tendriamos que ver si esto pasa con mas usuarios, o por ahi es algo que solo pasa con su cuenta.

**Comment by hugolatra** [comment]
Si, es raro. Ahora algunos pudieron anotarse, y por ejemplo a Nacho lo veo con foto, al resto no.

**Comment by GasparMDQ** [comment]
Al parecer, no estaba cargando la foto actualizada de los usuarios (por eso apuntaba a una version 'vieja' que no existe.
Tengo un parche listo, pero las fotos se van a ir actualizando a medida que la gente entre de nuevo a la aplicacion.
