### ISSUE TITLE
Problemas de login

### ISSUE THREAD

**Issue by hugolatra** [GasparMDQ/mdqrapp#18]
Me dicen al menos tres personas que probaron (Pablo Quattroquio, y dos mas con menos idea), que no se pueden loguear... aparece la pantalla del login, pero al entrar los datos no pasa de ahi. Segun Pablo, da "Internal Server Error", y un botón que al parecer dice Dismiss. Me mando una copia de pantalla.

Lo raro es que yo desde el Maxhon, y Cris desde el Chrome, pueden ingresar sin problema. Me lo reportaron con error desde IE, FF y Chrome.

![reporte1](https://cloud.githubusercontent.com/assets/7000470/9605831/571798ee-5096-11e5-8838-2fe887fc5823.jpg)

**Comment by hugolatra** [comment]
Al parecer es con el dominio registrado en fb... porque según Nacho, desde http://mdqrollers.herokuapp.com/ anda perfecto.

**Comment by jicasada** [comment]
Detalle del problema:
Uncaught SecurityError: Blocked a frame with origin "http://mdqrollers.herokuapp.com" from accessing a frame with origin "http://eventos.mdqrollers.com". Protocols, domains, and ports must match.

**Comment by GasparMDQ** [comment]
A diferencia de la api de autorizacion de google, facebook no parece permitirme apuntar una misma app a dos dominios distintos.
Ya que el host en mdqrollers.com no soporta nodeJs, vamos a tener que usar el dominio en heroku por ahora. 

Hugo, corregi el evento para que se anoten en http://mdqrollers.herokuapp.com/ en vez de la otra URL.
