### ISSUE TITLE
Muestra hab y micro de pax que fueron desmarcados del pago total

### ISSUE THREAD

**Issue by hugolatra** [GasparMDQ/mdqrapp#19]
Desmarco el pago total de un pasajero y se sigue viendo la hab  y el lugar del micro que ya habia tomado (solo pasa en pax que por error les marque todo el pago y despues los desmarco), es casi irrelevante.

**Comment by GasparMDQ** [comment]
La palabra clave es 'por error marque todo el pago'. La forma de bajarlos de los micros y habitaciones es sacarlos del evento.
Si les revocas el pago, eso no afecta a las selecciones que hubieran hecho.
Si son solo un par de casos aislados, podes borrar directamente la habitacion o micro en cuestion, y lo creas de nuevo.
